[[plugins]]
package = "netlify-plugin-cache"

[plugins.inputs]
paths = [ 
  "public/assets/blog",    # Optimized blog images
  "public/assets/images",  # Other website images
  ".cache"                 # Remote Assets 
]