[[plugins]]
package = "netlify-plugin-cache"

[plugins.inputs]
paths = [
"public/assets/images", # Processed images - adjust to match your outputDir
"public/assets/blog",   # Ensure blog images are cached
".cache" # Remote Assets
]